### ISSUE TITLE
Remove (or configure) Compressed Row Format in MySQL

### ISSUE THREAD

**Issue by martinpeck** [icokpy/ok#10]

**Comment by c-w** [comment]
Code pointer: https://github.com/Cal-CS-61A-Staff/ok/blob/547ff5287906f38463ffe8a0c9df3fc995026bbe/server/models.py#L961

The default value for the row format is called `default`: https://dev.mysql.com/doc/refman/5.7/en/innodb-row-format-specification.html

**Comment by c-w** [comment]
https://github.com/icokpy/ok/pull/22
