### ISSUE TITLE
Add Travis tests that use MySQL

### ISSUE THREAD

**Issue by martinpeck** [icokpy/ok#11]

**Comment by c-w** [comment]
This should be as simple as adding a new SQLALCHEMY_DATABASE_URI to the Travis test matrix: https://github.com/Cal-CS-61A-Staff/ok/blob/547ff5287906f38463ffe8a0c9df3fc995026bbe/.travis.yml#L13

The test will have to be against a live Azure deployment. We can use the Travis gem to encrypt the connection string and check it into the repo. https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by c-w** [comment]
We ran the tests locally and they pass and we don't want to maintain a live instance that the integration tests hit (would likely raise eyebrows in pull request back to upstream repo) so closing this one.
