### ISSUE TITLE
Enable SSL connection on redis

### ISSUE THREAD

**Issue by marrobi** [icokpy/ok#13]

**Comment by c-w** [comment]
Ok.py is using Flask-RQ to connect to Redis: https://github.com/Cal-CS-61A-Staff/ok/blob/547ff5287906f38463ffe8a0c9df3fc995026bbe/requirements.txt#L47

Flask-RQ can create the underlying redis connection via URL or HOST/PORT parameters: https://github.com/mattupstate/flask-rq/blob/52c1e8fa211d4c7421fb3b827dd99bb1a2d32759/flask_rq.py#L39-L46

The redis library to create the underlying connection which supports ssl via the `rediss://` scheme: https://github.com/andymccurdy/redis-py/blob/5109cb4f6b610e8d5949716a16435afbbf35075a/redis/connection.py#L789-L797

**Comment by c-w** [comment]
We have two ways to implement this:

1) Add an option to Flask-RQ to pass-through an "enable SSL" variable.
2) Refactor ok.py to use a connection string instead of host/password/user variables.

**Comment by martinpeck** [comment]
I'll pick this up and take a look at the options

**Comment by martinpeck** [comment]
Closing this issue as the works is done.
