### ISSUE TITLE
Modify logging and crash reporting (Sentry, GClouds) to use Application Insights

### ISSUE THREAD

**Issue by martinpeck** [icokpy/ok#18]

**Comment by c-w** [comment]
AppInsights Python SDK: https://github.com/Microsoft/ApplicationInsights-Python

```py
from applicationinsights.requests import WSGIApplication

# instantiate the Flask application and wrap its WSGI application
app = Flask(__name__)
app.wsgi_app = WSGIApplication('<YOUR INSTRUMENTATION KEY GOES HERE>', app.wsgi_app)
```

**Comment by c-w** [comment]
Existing Sentry setup code: https://github.com/Cal-CS-61A-Staff/ok/blob/547ff5287906f38463ffe8a0c9df3fc995026bbe/server/extensions.py#L26-L27

**Comment by c-w** [comment]
https://github.com/icokpy/ok/pull/29

**Comment by c-w** [comment]
@navjotk Were you able to verify that the telemetry shows up in your AppInsights resource?

**Comment by c-w** [comment]
Verified that the telemetry shows up.
