### ISSUE TITLE
Add support for Azure MySQL service

### ISSUE THREAD

**Issue by marrobi** [icokpy/ok#3]

**Comment by c-w** [comment]
#22

**Comment by marrobi** [comment]
Need to handle the initial creation of a database. I did this here [https://github.com/Cal-CS-61A-Staff/ok/compare/master...marrobi:marcus_azure](https://github.com/Cal-CS-61A-Staff/ok/compare/master...marrobi:marcus_azure ) but this is my hacky attempt to resolve. Two option I can think of:

1. Create tables if they dont exist
2. As part of deployment spin up a container to create the tables. This seems hacky too.

**Comment by marrobi** [comment]
Will do no 2, created new issue.

**Comment by c-w** [comment]
We decided to handle this via a custom script to manage the creation of the database and other resources like storage containers.
