### ISSUE TITLE
Verify refactor of settings files do not change the settings in each file, or verifiy that it isnt an issue if they do.

### ISSUE THREAD

**Issue by marrobi** [icokpy/ok#65]
For example https://github.com/icokpy/ok/blob/master/server/settings/simple.py, STORAGE_PROVIDER = 'LOCAL' . In the refactored it uses the environment variable.

**Comment by marrobi** [comment]
@c-w @liliankasem  is this now complete? Thanks.

**Comment by liliankasem** [comment]
They did change some settings, @c-w put out a PR into the original okpy master to make sure the config remaster matches the old settings values. Whether that was an issue or not @c-w can confirm?

PR: https://github.com/Cal-CS-61A-Staff/ok/pull/1264

**Comment by c-w** [comment]
The PR was merged.
