### ISSUE TITLE
Add tests for Azure Storage

### ISSUE THREAD

**Issue by martinpeck** [icokpy/ok#8]

**Comment by martinpeck** [comment]
The expectation is that the tests will fail, and that we will then need to apply a patched libcloud library to get them working again.

**Comment by c-w** [comment]
Here is the patched version `git+https://github.com/jmspring/libcloud@issue_933_azure_crash_v2.3.0-base`

**Comment by c-w** [comment]
Done in https://github.com/icokpy/ok/tree/azure_storage
Currently 5 failing tests which will be fixed after implementing #17
